# Generated by Django 3.1.7 on 2021-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=1, help_text='Say something about you.', max_length=1000, null=1),
            preserve_default=1,
        ),
    ]
