# Generated by Django 3.1.7 on 2021-09-06 09:33

from django.db import migrations, models
import fitness.models
import fitness.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_auto_20210906_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=fitness.models.tomorrow, validators=[fitness.validators.validate_date]),
        ),
    ]
